In [9]:
from astropy.table import Table
import pyvo


"""Get information of galaxies in the fornax cluster from SIMBAD"""

'Get information of galaxies in the fornax cluster from SIMBAD'

In [10]:
# Make the TAP service object
service = pyvo.dal.TAPService ("http://simbad.u-strasbg.fr/simbad/sim-tap")

In [6]:
# Query the TAP service with a simple ADQL query.
result = service.search ("""
SELECT TOP 15
main_id,oid,ra,dec,galdim_majaxis
FROM basic
WHERE 1=CONTAINS(
POINT('',ra, dec),
CIRCLE('',54.81426, -35.4652, 0.6))
AND galdim_majaxis>0.4 """)
print ( result )

<Table length=15>
       main_id          oid    ...         dec         galdim_majaxis
                               ...         deg             arcmin
        object         int64   ...       float64          float32
--------------------- -------- ... ------------------- --------------
2XMM J033938.8-352509   669322 ...  -35.42077777777777           0.47
         LEDA  644537   669281 ...  -35.79361111111111           0.54
            NGC  1389   669009 ...   -35.7460754622463           1.38
         LEDA   13449   670611 ...  -35.37102777777778         0.5593
              FCC 226   669048 ...          -35.023227           0.72
         LEDA   13452   669017 ... -35.724722222222226            1.1
            NGC  1396   669096 ...   -35.4398991268709          0.437
            NGC  1404   671055 ...  -35.59439166666667           4.79
   APMBGC 358-023+034  5132002 ...  -35.62730555555556            1.4
 [VPL2017] FDS11 LSB1 13286199 ...             -35.697           3.88
         LEDA   74930   669062 ...          -35.443142      0.6314667
            NGC  1387   669243 ...   -35.5065811072567           1.85
         LEDA   74923   669061 ...          -35.292364         0.4457
         LEDA  176559   669585 ...  -35.34861111111111           0.45
            NGC  1399   671066 ... -35.450741666666666           7.59

In [11]:
# Upload Your list of Names
a=['3C 10','M 2','HD 3']
table = Table([a], names=['myname'], meta={'meta':'first table'})

In [20]:
from astroquery.utils.tap.core import TapPlus
service = TapPlus ("http://simbad.u-strasbg.fr/simbad/sim-tap")

Created TAP+ (v20200428.1) - Connection:
	Host: simbad.u-strasbg.fr
	Use HTTPS: False
	Port: 80
	SSL Port: 443

In [22]:
full_qualified_table_name = 'TAP_UPLOAD.my_table'

query = 'SELECT * FROM ' + full_qualified_table_name
job = service.launch_job(query=query,upload_resource=table, \
upload_table_name="my_table", verbose=True)

results = job.get_results()
print(results)

Launched query: 'SELECT  TOP 2000 * FROM TAP_UPLOAD.my_table'
------>http
host = simbad.u-strasbg.fr:80
context = /simbad/sim-tap/sync
Content-type = multipart/form-data; boundary====1635174662427===
200 200
[('Date', 'Mon, 25 Oct 2021 15:11:02 GMT'), ('Server', 'Apache'), ('Set-Cookie', 'JSESSIONID=80E90CF06D074AE12FC822B519E51AA2.new; Path=/simbad; HttpOnly'), ('Access-Control-Allow-Origin', '*'), ('Transfer-Encoding', 'chunked'), ('Content-Type', 'application/x-votable+xml;charset=UTF-8')]
Retrieving sync. results...
Query finished.
myname
------
 3C 10
   M 2
  HD 3

In [25]:

query = 'SELECT myname, main_id AS "simbadName", rvz_redshift, rvz_bibcode FROM basic JOIN ident ON oid=oidref RIGHT JOIN ' + full_qualified_table_name + ' ON myname=id'
job = service.launch_job(query=query,upload_resource=table, \
upload_table_name="my_table")

results = job.get_results()
print(results)

myname simbadName       rvz_redshift          rvz_bibcode
------ ---------- ----------------------- -------------------
 3C 10   SN 1572A                      --
   M 2      M   2 -1.2408507355843312e-05 2019MNRAS.482.5138B
  HD 3  HD      3 -6.0039734750771956e-05 2006AstL...32..759G